import matplotlib.pyplot as plt
import seaborn as sns
print("input cypher to analyse")
x = input()
cypher = ','.join(x)
total = []
a = cypher.count("a")
b = cypher.count("b")
c = cypher.count("c")
d = cypher.count("d")
e = cypher.count("e")
f = cypher.count("f")
g = cypher.count("g")
h = cypher.count("h")
i = cypher.count("i")
j = cypher.count("j")
k = cypher.count("k")
l = cypher.count("l")
m = cypher.count("m")
n = cypher.count("n")
o = cypher.count("o")
p = cypher.count("p")
q = cypher.count("q")
r = cypher.count("r")
s = cypher.count("s")
t = cypher.count("t")
u = cypher.count("u")
v = cypher.count("v")
w = cypher.count("w")
x = cypher.count("x")
y = cypher.count("y")
z = cypher.count("z")
letters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
total.append(a)
total.append(b)
total.append(c)
total.append(d)
total.append(e)
total.append(f)
total.append(g)
total.append(h)
total.append(i)
total.append(j)
total.append(k)
total.append(l)
total.append(m)
total.append(n)
total.append(o)
total.append(p)
total.append(q)
total.append(r)
total.append(s)
total.append(t)
total.append(u)
total.append(v)
total.append(w)
total.append(x)
total.append(y)
total.append(z)
plt.bar(letters, total)
plt.show()
